name: Train Regression Model

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci-train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Train model (Linear)
        run: python -m src.train --model linear

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-and-metrics
          path: |
            models/
            models/metrics.json
